pool: 'dhl-build-pool'

# do not trigger on pr, because that means it will be done twice.
pr: none

steps:
    - task: Docker@2
      displayName: Login to dockerhub (push)
      inputs:
          command: login
          containerRegistry: dhl-docker-hub-pusher-selfbilling
    - script: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --use --name multi-arch-builder
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --tag dhlparcel/docker-postgres-for-testing:$(Build.BuildNumber) \
          --tag dhlparcel/docker-postgres-for-testing:latest \
          . \
          --push
        docker buildx uninstall
        docker buildx rm multi-arch-builder
      displayName: "Build docker postgres for testing"